CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	username VARCHAR(100) UNIQUE NOT NULL, -- use this for email
	password VARCHAR(255) NOT NULL,
	is_member BOOLEAN DEFAULT FALSE,
	is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE messages (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	text TEXT NOT NULL,
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	author_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
